name: Deploy Infra - Function, Logic Apps, SQL DB, Storage

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

env:
  AZURE_APP_NAME: 'ai-claims-automation'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'
  AZURE_RESOURCE_GROUP: 'rg-ai-claims-automation'
  AZURE_LOCATION: 'North Europe'
  SQL_ADMIN_LOGIN: ${{ secrets.SQLADMINLOGIN }}
  SQL_ADMIN_PASSWORD: ${{ secrets.SQLADMINPASSWORD }}
  RG_TAGS: "environment=dev SecurityControl=Ignore"
  SERVICE_PRINCIPAL_OID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      functionAppName: ${{ steps.bicep-deploy.outputs.functionAppName }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Debug - Check if secret exists'
      run: |
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "AZURE_CREDENTIALS secret is empty or not found"
          exit 1
        else
          echo "AZURE_CREDENTIALS secret exists (length: ${#AZURE_CREDENTIALS})"
        fi
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Create Resource Group'
      run: |
        az group create \
          --name ${{ env.AZURE_RESOURCE_GROUP }} \
          --location "${{ env.AZURE_LOCATION }}" \
          --tags ${{ env.RG_TAGS }}

    - name: 'Deploy Infrastructure'
      id: bicep-deploy
      run: |
        az deployment group create \
          --name main \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file infra/main.bicep \
          --parameters infra/main.bicepparam \
          --parameters sqlAdminLogin=$SQL_ADMIN_LOGIN sqlAdminPassword=$SQL_ADMIN_PASSWORD \
          --tags ${{ env.RG_TAGS }} \
          --verbose --debug
        
        # Get outputs separately to avoid consumption issue
        outputs=$(az deployment group show \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name main \
          --query 'properties.outputs' \
          --output json --verbose --debug)
        
        echo "Deployment outputs: $outputs"
        
        functionAppName=$(echo $outputs | jq -r '.functionAppName.value // empty')
        
        if [ -z "$functionAppName" ] || [ "$functionAppName" = "null" ]; then
          echo "Error: Could not extract functionAppName from deployment outputs"
          echo "Raw outputs: $outputs"
          exit 1
        fi
        
        echo "Extracted function app name: $functionAppName"
        echo "functionAppName=$functionAppName" >> $GITHUB_OUTPUT

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: deploy-infrastructure
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Tests'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        # Add your test commands here
        # python -m pytest tests/
        popd

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: ${{ needs.deploy-infrastructure.outputs.functionAppName }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true